### ISSUE TITLE
Add second argument 'soundEnabledProperty' to Sound?

### ISSUE THREAD

**Issue by samreid** [phetsims/vibe#11]
I think it will clean up several usage sites if we can add a second parameter to the Sound constructor, which is a Property<Boolean> for soundEnabledProperty.  This will be an optional parameter, and when the sound is played, if this parameter was provided the sound will only be played if the sound was enabled.

An alternative would be to add a Static method on Sound that turns all sound on/off.  Let's discuss.

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/vibe/issues/12. I'm not convinced that having a global soundEnabledProperty is a good idea.

**Comment by jbphet** [comment]
Vibe is not going to be used as our main sound library moving forward, and global on/off of sound has been implemented in tambo, which is the new sound library.  Eventually, vibe will be deprecated and, with that in mind, it's not worth spending any effort on a four-year-old GitHub issue.  Closing.
