### ISSUE TITLE
audioEnabledProperty defaults to true.  Won't some sims want a default of false?

### ISSUE THREAD

**Issue by samreid** [phetsims/vibe#12]
soundEnabledProperty defaults to true.  Won't some sims want a default of false?

**Comment by pixelzoom** [comment]
> if the sound is turned off anywhere in the sim, it should be turned off everywhere in the sim

I'm not convinced that we want our implementation to be based on that assumption.

**Comment by jbphet** [comment]
There has been a lot of development of sound support, most of it in the tambo repo, and the enabled behavior is now done as described in https://github.com/phetsims/tambo/issues/11.  Closing.
