### ISSUE TITLE
clean up vibe

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vibe#14]
vibe needs some clean up.

✓ test/play_sound.hmtl is broken (AXON/Property not found)
• there are multiple .html files in experiments/, with little/no documentation about what they are for
• experiments/basic_howler_test.html is broken (cannot read property '1' of null)
✓ tests/play_sound.hmtl should get requirejs from sherpa and delete lib/
X combine tests/ and experiments/ ?
✓ put all source code under js/
✓ .iml file should not be checked in
✓ holwer.js should be in sherpa, not in experiments/
✓ base64-binary.js should be in sherpa, not in experiments/
✓ missing .gitignore
✓ missing Gruntfile
✓ missing package.json
✓ missing entries in audio/license.txt

**Comment by pixelzoom** [comment]
If howler.js is continued to be used, it should be moved to sherpa, and added to PhET's spreadsheet of 3rd-party libs/licenses.

**Comment by pixelzoom** [comment]
I added .gitignore and deleted vegas.iml.

**Comment by pixelzoom** [comment]
Re "combine tests/ and experiments/ ", @jbphet said:
> Experiments was a record of a number of things that I needed to try in order to get things working, and I hadn't intended to maintain them, but wanted them for historical reference if needed.  Tests were intented to be maintained.

**Comment by pixelzoom** [comment]
I did most of the cleanup, including making the test work (since @jbphet said it was intended to be maintained.) I put a check mark next to the things that are done above.

The remaining cleanup will need to be done by @jbphet. It's all related to stuff in the experiments/, and since some of that is broken, I can't proceed.

**Comment by pixelzoom** [comment]
While reformatting code for https://github.com/phetsims/joist/issues/173, I accidentally reformatted howler.js and base64-binary.js, because they should not be here.  I deleted base64-binary.js and replaced with ../../sherpa/base64binary.js.  I moved howler.js to sherpa, and added it to "PhET HTML5 Simulation 3rd Party Libararies", https://docs.google.com/spreadsheets/d/1XWlHFidztUT6ARb7yHQ1Naepd6L0x9LF94AAoKHGaWg/edit#gid=0. 

Note that while I attempted to fix experiments/*.html to reflect the new location of these libraries, I could not test because the experiments were in a broken state.

**Comment by pixelzoom** [comment]
Remaining work is to document the experiments and make them work.

**Comment by pixelzoom** [comment]
Commits that were made with wrong issue number: https://github.com/phetsims/vibe/commit/eb121c57ea54c08bbe03320d358f304f54e1eb5d, https://github.com/phetsims/vibe/commit/8b686b0ad3b75a6f3b6162aab8d64d46ac3ade48

**Comment by pixelzoom** [comment]
I took a stab at making the experiments work. Bu the following are still broken:

basic-howler-test.html
combine-web-audio-and-html5-audio.html
ipad-base64-audio-test-02.html

**Comment by samreid** [comment]
@jbphet may I please delete howler?

**Comment by jbphet** [comment]
The "Howler" library has been removed, and I also went ahead and deleted the experiments.  Most of them are out of date at this point, since web audio has evolved a lot since this library was created.  That should cover everything logged in this issue is needing cleanup, closing.
