### ISSUE TITLE
Investigate built-in replacements for base64binary.js

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/vibe#15]
In Node.js, this would be ```new Buffer( base64String, 'base64' )``` to decode, ```buffer.toString( 'base64' )``` to encode.

In the browser, atob() and btoa() handle the same type of thing.

Would allow us to remove the base64binary.js dependency.

**Comment by pixelzoom** [comment]
Somewhat related to https://github.com/phetsims/chipper/issues/32

**Comment by pixelzoom** [comment]
@jbphet I see that you removed base64binary.js. Can this issue be closed?

**Comment by jbphet** [comment]
base64binary has been removed as a dependency, and I've done what I think is needed to remove it from the dependency repo (sherpa), including the license generation.  Closing.
