### ISSUE TITLE
vibe build fails

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vibe#16]
```
% grunt
Running "jshint:allFiles" (jshint) task
>> 0 files linted. Please check your ignored files.

Running "clean" task

Running "set-preload" task

Running "set-third-party-licenses" task

Running "before-requirejs-build" task
Warning: phetLibs missing from package.json Use --force to continue.

Aborted due to warnings.
%
```

**Comment by pixelzoom** [comment]
I tried to fix this, but there are lots of other problems here...

• missing simTitleStringKey in package.json
• file names don't match repo name (vibe-test-main.js, vibe-test-config.js, vibe-test.html)
• doesn't use PhET framework, so can't find  global.phet.strings

Assigning to @jbphet to decide how to proceed.  Note that this demo is now in chipper/data/active-runnables, so we're going to continue to hit this failure as part of day-to-day regression testing.

**Comment by pixelzoom** [comment]
Recommend to convert this to use the PhET framework (use simula-rasa template).

**Comment by jbphet** [comment]
This test/demo has now been converted to use the PhET framework.  It builds and runs for me.  Assigning back to @pixelzoom to test the build and make sure it all looks copacetic.  He can feel free to close if so.

**Comment by pixelzoom** [comment]
Runs and builds for me. Closing.
