### ISSUE TITLE
eliminate vibe-specific code in reportUnusedMedia.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vibe#17]
I noticed this bit of vibe-specific code in the audio.js plugin:

```js
      // The only exception is VIBE/empty.mp3 which doesn't require an ogg version (WHY?)
      if ( key !== 'VIBE/empty.mp3' ) {
        if ( endsWith( key, '.mp3' ) || endsWith( key, '.ogg' ) ) {
          key = key.substring( 0, key.length - 4 );
        }
      }
```

This should be fixed.

**Comment by jbphet** [comment]
Hmmm.  I'm confused by this.  I'm not seeing the code described in audio.js, and I scanned through the recent history and didn't see a place where it was removed.  @pixelzoom - what am I missing?

**Comment by samreid** [comment]
Perhaps @pixelzoom was referring to code in the reportUnusedMedia.js file, which was removed by @samreid in 78f10d9ab62821bce5415dfd6d33978f8f0a9e1b as part of #261  Let's reassign to @pixelzoom and ask.

**Comment by pixelzoom** [comment]
Indeed, I meant reportUnusedMedia.js.

**Comment by samreid** [comment]
I think this was addressed in https://github.com/phetsims/chipper/issues/261, can we close this one?

**Comment by pixelzoom** [comment]
Yup.
