### ISSUE TITLE
add demo app to phetmarks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vibe#23]

**Comment by jbphet** [comment]
It's there as far as I can tell, and was added back in July of this year.  See https://github.com/phetsims/phetmarks/commit/1822b9b798f6503132e9147cfdcd5be5383ae009.  Am I missing something?

**Comment by pixelzoom** [comment]
Sorry, I should have been more specific.  At the top of phetmarks, there's an entry for every common repo that has an "example" application.  See screenshot below.  Vibe's example is absent.  

![screenshot_106](https://cloud.githubusercontent.com/assets/3046552/11537819/2048bfd0-98dc-11e5-855c-512c4af51473.png)

**Comment by jbphet** [comment]
Got it, and did it.  Closing.
