### ISSUE TITLE
instrument the "continue" button at the end of a game

### ISSUE THREAD

**Issue by samreid** [phetsims/vibe#25]
From https://github.com/phetsims/build-an-atom/issues/107, we need to instrument the continue button at the end of a game.

**Comment by samreid** [comment]
I'm demoting this priority until publication issues are sorted out.

**Comment by jbphet** [comment]
@samreid - should this issue be in the @vegas repo?

**Comment by samreid** [comment]
Yes, thanks!  I'll move it soon.

Sam

On Jan 19, 2016, at 9:38 AM, John B <notifications@github.com<mailto:notifications@github.com>> wrote:


@samreid<https://github.com/samreid> - should this issue be in the @vegas<https://github.com/vegas> repo?

-

**Comment by samreid** [comment]
Moved to https://github.com/phetsims/vegas/issues/48, closing.
