### ISSUE TITLE
replace explicit prototype assignment in Sound.js with inherit(Object,...)

### ISSUE THREAD

**Issue by jbphet** [phetsims/vibe#26]
See https://github.com/phetsims/graphing-lines/issues/13 for original discussion on this pattern.

**Comment by jbphet** [comment]
Fixed, assigning to @jessegreenberg for review (since it's common code).

**Comment by jessegreenberg** [comment]
Replacement of direct prototype assignment looks good, and I like the simultaneous documentation reformat :+1: Closing.
