### ISSUE TITLE
Vibe crashed phantom.js

### ISSUE THREAD

**Issue by samreid** [phetsims/vibe#27]
I'm investigating a build service with phantom.js, it is working nicely except vibe audio is crashing the service.

**Comment by samreid** [comment]
I committed short circuits above that make the tests work under phantom, @jbphet can you review?

**Comment by jbphet** [comment]
The changes look fine assuming we incorporate phantomjs into our development processes, but this is the first I've heard about it, so I don't know if using it is a forgone conclusion.  This issue should remain open until either we have decided to use it or not and, if not, these changes should be backed out to minimize cruft.

**Comment by samreid** [comment]
Question for developer meeting.  Do we want to port simulations to the new platform phantomjs for automated testing and continuous integration?  It would involve avoiding web audio, and some of the methods that are not supported such as Number.isInteger.

**Comment by pixelzoom** [comment]
> some of the methods that are not supported such as Number.isInteger

Use DOT.Util.isInteger

**Comment by samreid** [comment]
Consensus: we'll port to phantomjs, but we should also email them and ask them to support functions like `Number.isInteger` etc.

**Comment by samreid** [comment]
We are proceeding with aqua, hence the vibe fixes will remain here.  Further work in aqua issue mentioned above, closing.
