### ISSUE TITLE
Performance degradation on iPad dragging

### ISSUE THREAD

**Issue by samreid** [phetsims/vibe#3]
John Travoltage performance in dragging the leg is smooth in:
http://www.colorado.edu/physics/phet/dev/html/john-travoltage/0.0.0-dev.10/john-travoltage_en.html

and slow (like 2 frames per second) in:
http://www.colorado.edu/physics/phet/dev/html/john-travoltage/0.0.0-dev.11/john-travoltage_en.html

I tracked the problem to vibe's workaround for iOS/Safari.  Here is my conclusion from the Travoltage ticket https://github.com/phetsims/john-travoltage/issues/30:

This is very confusing, but if I use vibe/master (aka https://github.com/phetsims/vibe/commit/91a7145c36eafb4a28f32d9335a393c98f729e66) performance is chunky on dragging the leg or arm in Travoltage.  But if I add these two lines:

```javascript
  if ( platform.mobileSafari ) {
    +var silenceDomNode = document.createElement( 'audio' );
    +document.body.appendChild( silenceDomNode );
```

at the bottom, then performance becomes smooth again.  I am not sure why.

**Comment by jbphet** [comment]
I tested this issue on two different iPad 2's, one running iOS 7.1 ("Lave", which is an A1395) and one running iOS 8.3 ("Magnus", also an A1395).  The test was to load the current master version of the john-travoltage sim, which is version 1.2.0-dev.1, with profiler enabled, then move the foot back and forth at a moderately rapid rate until there was a steady stream of electrons going from the foot to the doorknob.  The following screenshot illustrates:
![jt-ipad-test](https://cloud.githubusercontent.com/assets/3082831/8289652/1b14687e-18db-11e5-92e9-cfedd2b4cbc3.PNG)
On both devices, there was no difference in the minimum frame rate with and without the lines of code that @samreid shows above, and both cases had a frame rate of well above 2 fps.  On Magnus, the min frame rate was 10fps (shown in the pic) and on Lave it was 18 fps.  In my opinion, the sim was still usable at the lowest frame rates.  On both, the frame rate recovered rapidly as soon as the dragging of the foot stopped.

While testing this, I also tried taking out the iOS workaround altogether, and it worked on Magnus with iOS 8.3 but failed (no sound) on iOS 7.1, so it looks like we can't remove the workaround just yet.  The min frame rate did not improve with the workaround removed.

**Comment by jbphet** [comment]
For good measure, I ran the same tests described above on an iPad 3 (Disessa, an A1416) running iOS 8.3.  The min frame rate was 10 fps, and it was the same with the workaround as it currently stands, with the workaround with @samreid's additional lines of code, and with the workaround completely removed.  Also, on this device, sound did not play when the workaround was removed.

**Comment by jbphet** [comment]
Based on the tests described above, I recommend simply closing this issue and not changing the workaround.  Assigning back to @samreid to see if he concurs.

**Comment by samreid** [comment]
Can you be specific about what you mean by "the workaround as it currently stands" and "not changing the workaround"?  What is this workaround?

**Comment by jbphet** [comment]
@samreid: The workaround is the one that you referred to in the initial creation of the issue when you said:

> I tracked the problem to vibe's workaround for iOS/Safari.

Its purpose is to make sound work on an iPad by playing silence the first time the user touches anything in the sim.  There is more info in the code comments.  It is currently on lines 182-196 Sound.js in the vibe repository.

**Comment by samreid** [comment]
Thanks for clarifying, I agree with your remarks here https://github.com/phetsims/vibe/issues/3#issuecomment-114221107.  Closing.
