### ISSUE TITLE
Change in Web Audio API broke all sims with audio on Safari

### ISSUE THREAD

**Issue by phet-steele** [phetsims/vibe#30]
Specifically on macOS 10.12.4 Safari 10.1 and mobile Safari iOS 10.3.1. Audio will not play and certain sims will become unresponsive.

See the changes to the API here: https://www.w3.org/TR/2012/WD-webaudio-20121213/#DeprecationNotes

See the potential fix here: https://github.com/phetsims/vibe/commit/3b54a8c42c7009d809b6064834d16430b2eb4729

@phet-steele has tested the fix on:

- Win 10 Edge, FF, Chrome
- macOS 10.12.4 Safari, FF, Chrome
- iOS 9.3.5 Safari
- iOS 10.3.1 Safari
- ChromeOS 57 & canary

And everything works!

@jbphet please review above the commit and changes. @jonathanolson will answer any of your questions!

**Comment by jbphet** [comment]
The commit looks good to me.  Now we need to decide if maintenance releases are necessary for all sims that use sound.

**Comment by jonathanolson** [comment]
I'm already in a maintenance release process, so integrating this fix doesn't sound hard at all.

**Comment by jonathanolson** [comment]
Deployed in maintenance releases, closing.

**Comment by jbphet** [comment]
Thanks @jonathanolson!
