### ISSUE TITLE
branch: vibe-tambo

### ISSUE THREAD

**Issue by samreid** [phetsims/vibe#34]
To support https://github.com/phetsims/vibe/issues/33

**Comment by jbphet** [comment]
Hey @samreid - I think that this branch can probably be deleted now.  True?

**Comment by samreid** [comment]
Yes, thanks!  I'll delete it.

**Comment by samreid** [comment]
Deleted, closing.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
