### ISSUE TITLE
audioVolume query parameter broken?

### ISSUE THREAD

**Issue by zepumph** [phetsims/vibe#36]
My aqua test server has been very loud for a while now, for example I would have thought that http://localhost/aqua/test-server/test-sims.html?ea&audioVolume=0&sound=muted&testDuration=10000&testConcurrentBuilds=4&brand=phet&fuzzMouse&testSims=ohms-law

Would not make noise, but it does for me.

Furthermore I searched the project for that parameter and seem to only find usages, no place where it is manipulating sound code (I think that's what I'm seeing at least).

![image](https://user-images.githubusercontent.com/6856943/46508856-f5ce9a80-c7eb-11e8-9221-33b12cd67d21.png)

**Comment by zepumph** [comment]
Works like a charm. Thank you ever so kindly.

**Comment by zepumph** [comment]
I see this line in Sound.js:

```
      phet.chipper.queryParameters.audioVolume === undefined ? 1 : phet.chipper.queryParameters.audioVolume,
```

And I am wondering why you have the undefined check. Aren't phet query parameters guaranteed to be defined at runtime since they are a preload?

On top of that, if you were worried about audioVolume being undefined, wouldn't you also be worried about the queryParameters not being defined, such that you should do null checks for all the objects in that call.

To sum up my thoughts, I would think that this would be a safe and clean option instead:

```
    gainNode.gain.setValueAtTime( phet.chipper.queryParameters.audioVolume, audioContext.currentTime );
```

Or if you are worried about undefined values you should check for everything:
```
      phet && phet.chipper && phet.chipper.queryParameters && phet.chipper.queryParameters.audioVolume === undefined ? 1 : phet.chipper.queryParameters.audioVolume 
```

Phetmarks works great though.

**Comment by jbphet** [comment]
> Aren't phet query parameters guaranteed to be defined at runtime since they are a preload?

Ah, good call @zepumph , I'd forgotten that the parameters in `initialize-globals.js` are guaranteed to have defined values.  I've simplified the handling.  Please test drive again and close if things look and sound good.
