### ISSUE TITLE
Firefox is about to implement initial audio blocking, we should test that we handle it

### ISSUE THREAD

**Issue by jbphet** [phetsims/vibe#37]
I just saw [an article about Firefox starting to auto-block audio and video on web pages](https://hacks.mozilla.org/2019/02/firefox-66-to-block-automatically-playing-audible-video-and-audio/) until the user interacts with the page.  Hopefully, this will be handled by the code already in place to handle similar behaviors seen in Chrome and Safari, see https://github.com/phetsims/vibe/issues/32, but we should test to make sure.

There is a parallel issue in the tambo repo, see https://github.com/phetsims/tambo/issues/58.

**Comment by jbphet** [comment]
Assigning to @phet-steele at @ariel-phet's suggestion.

@phet-steele - Can you please get set up to test with the upcoming version of Firefox (which I believe is v66) and test the sims that use the vibe libary and make sure they work?  Some examples are the game screens on Balancing Act and Build and Atom.  The main screen of Plinko also has sound capability.  As mentioned in the related tambo issue, please check on both Windows and Mac if possible and, if not, assign back to @ariel-phet for additional followup. Thanks.

**Comment by phet-steele** [comment]
Testing suggested sims on Windows 10 with FF 66.0b7: sound works.

However, there was a neat interaction with the dev tools. Opening dev tools for the first time mutes all sound. Closing the dev tools, then opening the dev tools a second time brings sound back. It will even play all the sound it "queued" when sound was muted. This cycle repeats on each successive opening/closing of the dev tool. Hopefully our users on FF don't use the dev tools often 😉.

Mac testing will soon follow.

**Comment by jbphet** [comment]
Since sound will all be using tambo in the future, the fact that it works is sufficient.  I'm not going to worry about the interaction with the dev tools and the vibe version of the sound library.  I'll do some investigation of this for tambo.  Closing.
