### ISSUE TITLE
Full screen gets rid of sound

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vibe#38]
**Device**
Dirac
**OS**
Mac OS 10.11.6
**Browser**
Safari 11.1.2
**Problem Description**
For https://github.com/phetsims/QA/issues/231, did not seem to happen in other sims in this suite for some reason.  Did seem to occur in published version.  Doesn't happen on Mac OS 10.10, but does on versions after that.
Sometimes, when entering full screen mode, the sound in the sim will cut out.  When opening or closing tabs after this (such as when using the report a problem feature) one of the sounds that didn't play before suddenly will.  May happen in other circumstances than described here, but this is the consistent method I discovered.
**Steps to reproduce**
1. Load sim/reload sim in safari
2. Go to first level of a game
3. Get answer wrong
4. Click try again (this is an important step)
5. Enter full screen
6. Click check on the same wrong answer and listen

**Troubleshooting**

<details>

Name: ‪Area Model Multiplication‬
URL: https://phet-dev.colorado.edu/html/area-model-multiplication/1.1.0-rc.2/phet/area-model-multiplication_en_phet.html
Version: 1.1.0-rc.2 2018-12-03 19:28:07 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15
Language: en-US
Window: 1185x716
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.52)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"area-model-common":{"sha":"72f057d1","branch":"HEAD"},"area-model-multiplication":{"sha":"aeec4a9d","branch":"HEAD"},"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"61dd41f7","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"0097c5ac","branch":"HEAD"},"dot":{"sha":"266d3b7a","branch":"HEAD"},"joist":{"sha":"88658dbb","branch":"HEAD"},"kite":{"sha":"f3e96e5b","branch":"HEAD"},"phet-core":{"sha":"2e54db08","branch":"HEAD"},"phet-io":{"sha":"1acc6dc2","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"HEAD"},"phet-io-wrappers":{"sha":"9d0c5205","branch":"HEAD"},"phetcommon":{"sha":"869b2561","branch":"HEAD"},"query-string-machine":{"sha":"c4d4a81e","branch":"HEAD"},"scenery":{"sha":"4618d52a","branch":"HEAD"},"scenery-phet":{"sha":"e5fa975a","branch":"HEAD"},"sherpa":{"sha":"2134a0d1","branch":"HEAD"},"sun":{"sha":"6887a29a","branch":"HEAD"},"tambo":{"sha":"9b56e6cd","branch":"HEAD"},"tandem":{"sha":"7134621c","branch":"HEAD"},"twixt":{"sha":"3ef1cdc0","branch":"HEAD"},"vegas":{"sha":"9b35cba0","branch":"HEAD"},"vibe":{"sha":"474ae764","branch":"HEAD"}}

</details>

**Comment by jbphet** [comment]
In https://github.com/phetsims/vegas/issues/77 the `GameAudioPlayer` type was rewritten to use the tambo library instead of vibe.  Since tambo has built-in support for handling Safari's tendency to disable the audio context in full screen mode, the problem described in this GitHub issue should be gone for all simulations that use game sound.  @KatieWoe - please have QA test this and see if it is resolved.

**Comment by KatieWoe** [comment]
Looks good on a quick check on master.

**Comment by jbphet** [comment]
Cool.  Closing.
