### ISSUE TITLE
Reduce the size of the audio effects to the minimum with acceptable sound quality

### ISSUE THREAD

**Issue by jbphet** [phetsims/vibe#7]
It may well be possible to use sound effects encoded at a rate that reduces the size of the files.

**Comment by pixelzoom** [comment]
Do we want to do this before "Summer 2015 redeploy"?

**Comment by jbphet** [comment]
The primary audio effects in the common code are those used in the game.  There are four sound effects: ding (correct answer), boing (incorrect answer), trumpet (finished level with some correct answers), and cheer (finished level with all correct answers). I normalized all four files to 0.0 dB (see https://github.com/phetsims/vegas/issues/35) and re-encoded them at 32kbps for MP3 and at quality=4 for Ogg Vorbis.  This reduced the sum total size for all eight files to be 100kb, which seems pretty reasonable.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to help determine how to test these sounds and see if the quality level is acceptable.  I'm thinking we should assign to @bryo5363 or @phet-steele, since they have some audio experience and young ears, and/or @pixelzoom since he also has audio experience.

**Comment by samreid** [comment]
Did you happen to jot down the sum total size before compression so we can see the difference?  I'm curious.

**Comment by oliver-phet** [comment]
I tested across my computer using internal speakers and microphone, and 2 iPads and the difference was not noticeable (great job @jbphet!). Closing.
