### ISSUE TITLE
sherpa/base64Binary.js is miscapitalized resulting in the ohms law sim not working on case sensitive filesystems

### ISSUE THREAD

**Issue by olleicua** [phetsims/vibe#8]
steps to reproduce:

1. `git clone git@github.com:phetsims/ohms-law.git`
2. clone other dependencies
3. open in a browser

error:

```
GET http://127.0.0.1:3000/PHET/sherpa/base64Binary.js 404 (Not Found) 
```

**Comment by pixelzoom** [comment]
@olleicua did this resolve the problem that you reported?

**Comment by jbphet** [comment]
Haven't heard anything back from @olleicua, and the dependency on base64binary has been removed so this shouldn't be an issue any longer.  Closing.

**Comment by olleicua** [comment]
Sorry, our project isn't on the latest version of Phet.  We just renamed the file and changed all of the references to it.
