### ISSUE TITLE
Audio not playing in development mode (i.e. unminified requirejs mode) on Firefox 27

### ISSUE THREAD

**Issue by samreid** [phetsims/vibe#9]
Vasily said:

1.       Sound in Firefox 27 doesn’t play

I use approach from https://github.com/phetsims/john-travoltage/blob/master/js/model/JohnTravoltageModel.js

 

In file https://github.com/phetsims/fraction-matcher/blob/master/js/model/FractionMatcherModel.js I initialize then (line 38)

And in file https://github.com/phetsims/fraction-matcher/blob/master/js/model/LevelModel.js I played them (line 143)

 

It works fine in Chrome and iPad. But with Firefox and Android there is a problem. The sound doesn’t play.

**Comment by jbphet** [comment]
I just tested the development (unminified) versions of john-travoltage, fraction-matcher, area-builder, and ohms-law on Windows 7 + Firefox 37.0.2 and on Mac OSX 10.10.2 + Firefox 36.0.1, and sound worked fine for all sims on both platforms.  Seems like this was a Firefox issue that has been resolved.  Closing.
